id: P006924
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:02.214036
source_metadata:
  id: bdr:W1KG16138
  title: ལེགས་བཤད་གསེར་ཕྲེང་།
  author: ''
  volumes:
    bfb22a624b0a4d168247f334157664e5:
      image_group_id: I1KG16141
      title: ''
      volume_number: 1
      total_pages: 642
      base_file: v001.txt
    5c0e96d4dd10431bb2da9f78e6136867:
      image_group_id: I1KG16142
      title: ''
      volume_number: 2
      total_pages: 548
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
