id: I594F9037
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:47:31+00:00'
last_modified: '2022-06-08T12:31:53.476399+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16138
  title: ལེགས་བཤད་གསེར་ཕྲེང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8A33:
      image_group_id: I1KG16141
      title: ''
      total_pages: 642
      order: 1
      base_file: 8A33.txt
    '4196':
      image_group_id: I1KG16142
      title: ''
      total_pages: 548
      order: 2
      base_file: 4196.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
