id: I594F9037
legacy_id: P006924
ocr_import_info:
  bdrc_scan_id: W1KG16138
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T20:44:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:40:05.145205+00:00'
last_modified: 2022-08-27 13:41:47.946019
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16138
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG16138
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལེགས་བཤད་གསེར་ཕྲེང་།
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9561566676655443
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG16141:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16141
      total_pages: 642
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16141.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9608395956898035
    legacy_id: v001
  I1KG16142:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16142
      total_pages: 548
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG16142.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9495414898956074
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
